apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cirros
  name: cirros-deployment
spec:
  selector:
    matchLabels:
      app: cirros
  replicas: 1
  template:
    metadata:
      annotations:
        kubernetes.io/target-runtime: virtlet.cloud
        VirtletVCPUCount: "1"
        VirtletDiskDriver: virtio
        VirtletSSHKeys: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJEcFDXEK2ZbX0ZLS1EIYFZRbDAcRfuVjpstSc0De8+sV1aiu+dePxdkuDRwqFtCyk6dEZkssjOkBXtri00MECLkir6FcH3kKOJtbJ6vy3uaJc9w1ERo+wyl6SkAh/+JTJkp7QRXj8oylW5E20LsbnA/dIwWzAF51PPwF7A7FtNg9DnwPqMkxFo1Th/buOMKbP5ZA1mmNNtmzbMpMfJATvVyiv3ccsSJKOiyQr6UG+j7sc/7jMVz5Xk34Vd0l8GwcB0334MchHckmqDB142h/NCWTr8oLakDNvkfC1YneAfAO41hDkUbxPtVBG5M/o7P4fxoqiHEX+ZLfRxDtHB53 me@localhost
      labels:
        app: cirros
    spec:
      nodeSelector:
        extraRuntime: virtlet
      containers:
      - name: cirros-vm
        image: virtlet.cloud/cirros
        imagePullPolicy: IfNotPresent
        tty: true
        stdin: true
        resources:
          limits:
            memory: 160Mi
