FROM ubuntu:18.04
MAINTAINER Yunwen Bai <yunwen.bai@futurewei.com>

# BUMP 23.11.2018

ENV DEBIAN_FRONTEND noninteractive

RUN echo deb-src http://archive.ubuntu.com/ubuntu/ bionic main universe restricted >>/etc/apt/sources.list && \
    echo deb-src http://archive.ubuntu.com/ubuntu/ bionic-updates main universe restricted >>/etc/apt/sources.list

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get -y build-dep libguestfs && \
    apt-get -y build-dep supermin && \
    apt-get install -y apt-utils git libjansson-dev libhivex-ocaml-dev libguestfs-tools 

# build libvirt 6.5.0
RUN apt-get install -y build-essential libsasl2-dev libdevmapper-dev libgnutls28-dev \
                       libxml2-dev e2fslibs-dev libcap-ng-dev libnl-3-dev \
                       libselinux1-dev libssh2-1-dev libsystemd-dev \
                       parted python2.7-dev libreadline-dev libxslt1-dev \
                       libtirpc-dev libnl-route-3-dev libxml2-utils xsltproc \
                       python-docutils docbook-xsl uuid-dev && \
    curl -O https://libvirt.org/sources/libvirt-6.5.0.tar.xz && \
    tar xf libvirt-6.5.0.tar.xz && \
    cd libvirt-6.5.0 && \
    mkdir build && cd build && \
    ../configure --disable-silent-rules --with-udev=no --with-pciaccess=no --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib/x86_64-linux-gnu&& \
    make && \
    make install && \
    make clean

# build qemu 5.0.0
RUN apt-get build-dep -y qemu && \
    apt-get install -y checkinstall && \
    curl -O https://download.qemu.org/qemu-5.0.0.tar.xz && \
    tar -xf qemu-5.0.0.tar.xz && \
    cd qemu-5.0.0 && \
    ./configure && \
    make && \
    checkinstall make install && \
    apt-get install ./*.deb && \
    make clean

RUN apt-get install -y openssl scrub syslinux \
                       apt-utils netbase iptables ebtables vncsnapshot \
                       socat netcat-openbsd \
                       acl attr binutils bsdmainutils btrfs-tools \
                       bzip2 cpio cryptsetup curl dosfstools extlinux \
                       file gawk gdisk genisoimage iproute2 \
                       isc-dhcp-client kmod less libaugeas0 \
                       bridge-utils \
                       lsscsi lvm2 lzop mdadm module-init-tools \
                       mtools ntfs-3g openssh-client parted psmisc \
                       udev xz-utils zerofree libjansson4 \
                       dnsmasq libpcap0.8 libnetcf1 dmidecode && \
                       apt-get clean

# some hack to fix latest libvirt config issues
RUN echo “libvirt-qemu:x:64055:123:Libvirt Qemu,,,:/var/lib/libvirt:/usr/sbin/nologin” >> /etc/passwd && \
    useradd libvirt-qemu


