network-config:
  config:
  - mac_address: "00:11:22:33:44:55"
    mtu: 1500
    name: cni0
    subnets:
    - address: 1.1.1.1
      netmask: 255.0.0.0
      routes:
      - gateway: 1.2.3.4
        netmask: 0.0.0.0
        network: 0.0.0.0
      type: static
    type: physical
  - address:
    - 1.2.3.4
    search:
    - some
    - search
    type: nameserver
  version: 1
